name: spartan_scout
description: Spartan Scout
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  cupertino_icons: ^1.0.5
  custom_qr_generator: ^0.1.2
  inkblob_navigation_bar: ^0.1.2
  modal_bottom_sheet: ^3.0.0-pre
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  jsonc: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/spartan-logo.png
    - assets/templates/
